name: oxidizr
adopt-info: oxidizr
summary: A tool for experimenting with Rust-based packages on Ubuntu
description: |
  `oxidizr` is a command-line utility for managing system experiments
  that replace traditional Unix utilities with modern Rust-based alternatives
  on Ubuntu systems.

license: Apache-2.0
contact: https://github.com/jnsgruk/oxidizr/issues
issues: https://github.com/jnsgruk/oxidizr/issues
source-code: https://github.com/jnsgruk/oxidizr

base: core24
confinement: classic
grade: stable
compression: lzo

platforms:
  amd64:
  arm64:

parts:
  oxidizr:
    plugin: rust
    source: .
    build-attributes:
      - enable-patchelf
    override-stage: |
      craftctl default
      bin_version="$($CRAFT_STAGE/bin/oxidizr --version | cut -d" " -f2)"
      craftctl set version="$bin_version"

apps:
  oxidizr:
    command: bin/oxidizr
    plugs:
      - home
      - network
      - network-bind
