name: CI (Push)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/_lint.yml

  test:
    name: Test
    uses: ./.github/workflows/_test.yml

  spread-matrix:
    name: Spread Matrix
    uses: ./.github/workflows/_spread-matrix.yml

  spread-tests:
    name: Spread tests
    uses: ./.github/workflows/_spread.yml
    needs:
      - test
      - lint
      - spread-matrix
    with:
      tests: ${{ needs.spread-matrix.outputs.tests }}
